
FROM nnurphy/ub
ARG chez_repo=cisco/ChezScheme
ARG idris_repo=idris-lang/Idris2
ARG github_header="Accept: application/vnd.github.v3+json"
ARG github_api=https://api.github.com/repos

RUN set -eux \
  ; apt-get update && apt-get -y install make gcc uuid-dev libncurses5-dev \
  ; cd / \
  ; chez_version=$(curl -sSL -H "'$github_header'" $github_api/${chez_repo}/releases | jq -r '.[0].tag_name') \
  ; wget -q https://github.com/cisco/ChezScheme/archive/${chez_version}.tar.gz \
  ; tar xvzf ${chez_version}.tar.gz \
  ; rm ${chez_version}.tar.gz \
  ; cd ChezScheme-$(echo $chez_version | sed 's/^v\(.*\)/\1/') \
  ; ./configure --threads --disable-x11 \
  ; make -j install \
  ; cd / \
  ; rm -rf ChezScheme-$(echo $chez_version | sed 's/^v\(.*\)/\1/')

RUN set -eux \
  ; cd / \
  ; idris_version=$(curl -sSL -H "'$github_header'" $github_api/${idris_repo}/releases | jq -r '.[0].tag_name') \
  ; git clone https://github.com/idris-lang/Idris2.git \
  ; cd /Idris2 \
  ; git checkout v0.3.0 \
  ; make bootstrap SCHEME=scheme \
  ; make install \
  ; cd / \
  ; rm -rf Idris2

ENTRYPOINT ["/root/.idris2/bin/idris2"]
