FROM nnurphy/idr:2

WORKDIR /root
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV TIMEZONE=Asia/Shanghai

COPY home /root/

RUN set -ex \
  ; apk update && apk upgrade \
  ; rm -rf /var/cache/apk/* \
  ; apk add --no-cache tzdata \
      sudo shadow pwgen xz zstd tree \
      curl wget socat rsync jq \
      bash zsh vim git tmux \
      openssh-client openssh-server openssl \
  ; ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
  ; echo "$TIMEZONE" > /etc/timezone \
  ; echo "%wheel ALL=(ALL) NOPASSWD: AL" >> /etc/sudoers \
  ; sed -i /etc/ssh/sshd_config \
        -e 's!.*\(AllowTcpForwarding\).*!\1 yes!' \
        -e 's!.*\(GatewayPorts\).*!\1 yes!' \
        -e 's!.*\(AuthorizedKeysFile\).*!\1 /etc/authorized_keys/%u!' \
        -e 's!.*\(ChallengeResponseAuthentication\).*yes!\1 no!' \
        -e 's!.*\(PasswordAuthentication\).*yes!\1 no!'

ENV just_version=0.5.10
ENV watchexec_version=1.12.0
ENV yq_version=3.2.0
ENV websocat_version=1.5.0
ENV wasmtime_version=v0.15.0

ARG just_url=https://github.com/casey/just/releases/download/v${just_version}/just-v${just_version}-x86_64-unknown-linux-musl.tar.gz
ARG watchexec_url=https://github.com/watchexec/watchexec/releases/download/${watchexec_version}/watchexec-${watchexec_version}-x86_64-unknown-linux-musl.tar.xz
ARG yq_url=https://github.com/mikefarah/yq/releases/download/${yq_version}/yq_linux_amd64
ARG websocat_url=https://github.com/vi/websocat/releases/download/v${websocat_version}/websocat_amd64-linux-static+udp
ARG wasmtime_url=https://github.com/bytecodealliance/wasmtime/releases/download/${wasmtime_version}/wasmtime-${wasmtime_version}-x86_64-linux.tar.xz

RUN set -ex \
  ; wget -q -O- ${just_url} \
    | tar zxf - -C /usr/local/bin just \
  ; wget -q -O- ${watchexec_url} \
    | tar Jxf - --strip-components=1 -C /usr/local/bin watchexec-${watchexec_version}-x86_64-unknown-linux-musl/watchexec \
  ; wget -q -O /usr/local/bin/yq ${yq_url} \
    ; chmod +x /usr/local/bin/yq \
  ; wget -q -O /usr/local/bin/websocat ${websocat_url} \
    ; chmod +x /usr/local/bin/websocat \
  ; wget -O- ${wasmtime_url} | tar Jxf - --strip-components=1 -C /usr/local/bin \
        wasmtime-${wasmtime_version}-x86_64-linux/wasmtime

ENV SSH_USERS=
ENV SSH_ENABLE_ROOT=

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]