FROM nnurphy/idr:1 as base
ARG VERSION=v0.2.1

WORKDIR /
RUN apt-get update && apt-get -y install build-essential git clang
RUN curl -sSLO https://github.com/cisco/ChezScheme/archive/v9.5.2.tar.gz && \
  tar xvzf v9.5.2.tar.gz && \
  cd ChezScheme-9.5.2 && \
  ./configure --threads && \
  make -j install
RUN git clone https://github.com/idris-lang/Idris2.git
WORKDIR /Idris2
RUN git checkout ${VERSION}
RUN make bootstrap SCHEME=chez
RUN make install

FROM nnurphy/ub
COPY --from=base /root/.idris2 /root/.idris2
ENTRYPOINT ["/root/.idris2/bin/idris2"]
