
FROM nnurphy/ub
ARG CHEZ_VERSION=9.5.2
ARG IDRIS_VERSION=0.2.1

RUN set -eux \
  ; apt-get update && apt-get -y install make clang uuid-dev libncurses5-dev \
  ; cd / \
  ; wget https://github.com/cisco/ChezScheme/archive/v${CHEZ_VERSION}.tar.gz \
  ; tar xvzf v${CHEZ_VERSION}.tar.gz \
  ; rm v${CHEZ_VERSION}.tar.gz \
  ; cd ChezScheme-${CHEZ_VERSION} \
  ; ./configure --threads --disable-x11 \
  ; make -j install \
  ; cd / \
  ; rm -rf ChezScheme-${CHEZ_VERSION}

RUN set -eux \
  ; cd / \
  ; git clone https://github.com/idris-lang/Idris2.git \
  ; cd /Idris2 \
  ; git checkout v${IDRIS_VERSION} \
  ; make bootstrap SCHEME=scheme \
  ; make install \
  ; cd / \
  ; rm -rf Idris2

ENTRYPOINT ["/root/.idris2/bin/idris2"]